In [1]:
import pandas as pd

In [2]:
df = pd.read_csv('Data.csv', encoding = "ISO-8859-1")
df.head()

Date  Label                                               Top1  \
0  2000-01-03      0  A 'hindrance to operations': extracts from the...   
1  2000-01-04      0                                          Scorecard   
2  2000-01-05      0                  Coventry caught on counter by Flo   
3  2000-01-06      1                      Pilgrim knows how to progress   
4  2000-01-07      1                               Hitches and Horlocks   

                                 Top2  \
0                           Scorecard   
1                 The best lake scene   
2  United's rivals on the road to Rio   
3                 Thatcher facing ban   
4      Beckham off but United survive   

                                            Top3  \
0                Hughes' instant hit buoys Blues   
1                  Leader: German sleaze inquiry   
2  Thatcher issues defence before trial by video   
3        McIlroy calls for Irish fighting spirit   
4                        Breast cancer screening   

                                            Top4  \
0       Jack gets his skates on at ice-cold Alex   
1                                  Cheerio, boyo   
2  Police help Smith lay down the law at Everton   
3                Leicester bin stadium blueprint   
4                                    Alan Parker   

                                          Top5  \
0       Chaos as Maracana builds up for United   
1                     The main recommendations   
2  Tale of Trautmann bears two more retellings   
3               United braced for Mexican wave   
4      Guardian readers: are you all whingers?   

                                                Top6  \
0  Depleted Leicester prevail as Elliott spoils E...   
1                             Has Cubie killed fees?   
2                                England on the rack   
3  Auntie back in fashion, even if the dress look...   
4                                   Hollywood Beyond   

                                              Top7  \
0                 Hungry Spurs sense rich pickings   
1                           Has Cubie killed fees?   
2  Pakistan retaliate with call for video of Walsh   
3                    Shoaib appeal goes to the top   
4                               Ashes and diamonds   

                                                Top8  ...  \
0                  Gunners so wide of an easy target  ...   
1                             Has Cubie killed fees?  ...   
2               Cullinan continues his Cape monopoly  ...   
3  Hussain hurt by 'shambles' but lays blame on e...  ...   
4                   Whingers - a formidable minority  ...   

                                               Top16  \
0           Flintoff injury piles on woe for England   
1                               On the critical list   
2                        South Melbourne (Australia)   
3  Putin admits Yeltsin quit to give him a head s...   
4                             Most everywhere:  UDIs   

                                               Top17  \
0  Hunters threaten Jospin with new battle of the...   
1                          The timing of their lives   
2                                    Necaxa (Mexico)   
3         BBC worst hit as digital TV begins to bite   
4                       Most wanted:  Chloe lunettes   

                                            Top18  \
0             Kohl's successor drawn into scandal   
1                                     Dear doctor   
2                             Real Madrid (Spain)   
3                     How much can you pay for...   
4  Return of the cane 'completely off the agenda'   

                                               Top19  \
0               The difference between men and women   
1  Irish court halts IRA man's extradition to Nor...   
2                          Raja Casablanca (Morocco)   
3                                 Christmas glitches   
4                   From Sleepy Hollow to Greeneland   

                         

In [3]:
df.tail()

Date  Label                                               Top1  \
4096  2016-06-27      0  Barclays and RBS shares suspended from trading...   
4097  2016-06-28      1  2,500 Scientists To Australia: If You Want To ...   
4098  2016-06-29      1                   Explosion At Airport In Istanbul   
4099  2016-06-30      1  Jamaica proposes marijuana dispensers for tour...   
4100  2016-07-01      1  A 117-year-old woman in Mexico City finally re...   

                                                   Top2  \
4096  Pope says Church should ask forgiveness from g...   
4097  The personal details of 112,000 French police ...   
4098  Yemeni former president: Terrorism is the offs...   
4099  Stephen Hawking says pollution and 'stupidity'...   
4100   IMF chief backs Athens as permanent Olympic host   

                                                   Top3  \
4096  Poland 'shocked' by xenophobic abuse of Poles ...   
4097  S&amp;P cuts United Kingdom sovereign credit r...   
4098  UK must accept freedom of movement to access E...   
4099  Boris Johnson says he will not run for Tory pa...   
4100  The president of France says if Brexit won, so...   

                                                   Top4  \
4096  There will be no second referendum, cabinet ag...   
4097                Huge helium deposit found in Africa   
4098  Devastated: scientists too late to captive bre...   
4099  Six gay men in Ivory Coast were abused and for...   
4100  British Man Who Must Give Police 24 Hours' Not...   

                                                   Top5  \
4096      Scotland welcome to join EU, Merkel ally says   
4097  CEO of the South African state broadcaster qui...   
4098  British Labor Party leader Jeremy Corbyn loses...   
4099  Switzerland denies citizenship to Muslim immig...   
4100  100+ Nobel laureates urge Greenpeace to stop o...   

                                                   Top6  \
4096  Sterling dips below Friday's 31-year low amid ...   
4097  Brexit cost investors $2 trillion, the worst o...   
4098  A Muslim Shop in the UK Was Just Firebombed Wh...   
4099  Palestinian terrorist stabs israeli teen girl ...   
4100  Brazil: Huge spike in number of police killing...   

                                                   Top7  \
4096  No negative news about South African President...   
4097  Hong Kong democracy activists call for return ...   
4098  Mexican Authorities Sexually Torture Women in ...   
4099  Puerto Rico will default on $1 billion of debt...   
4100  Austria's highest court annuls presidential el...   

                                                   Top8  ...  \
4096  Surge in Hate Crimes in the U.K. Following U.K...  ...   
4097  Brexit: Iceland president says UK can join 'tr...  ...   
4098            UK shares and pound continue to recover  ...   
4099  Republic of Ireland fans to be awarded medal f...  ...   
4100  Facebook wins privacy case, can track any Belg...  ...   

                                                  Top16  \
4096  German lawyers to probe Erdogan over alleged w...   
4097  US, Canada and Mexico pledge 50% of power from...   
4098  Escape Tunnel, Dug by Hand, Is Found at Holoca...   
4099  Googles free wifi at Indian railway stations i...   
4100  The United States has placed Myanmar, Uzbekist...   

                                                  Top17  \
4096  Boris Johnson says the UK will continue to "in...   
4097  There is increasing evidence that Australia is...   
4098  The land under Beijing is sinking by as much a...   
4099  Mounting evidence suggests 'hobbits' were wipe...   
4100  S&amp;P revises European Union credit rating t...   

                                                  Top18  \
4096  Richard Branson is calling on the UK governmen...   
4097  Richard Branson, the founder of Virgin Group, ...   
4098  Car bomb and Anti-Islamic attack on Mosque in ...   
4099  The men who carried out Tuesday's terror attac...   
4100  India gets $1 bil

In [4]:
train = df[df['Date'] < '20150101']
test = df[df['Date'] > '20141231']

In [5]:
#Removing punctuations

data = train.iloc[:, 2:]
data.replace("[^a-zA-Z]", " ", regex = True, inplace = True)

#Renaming column names for ease of access

new_index = [str(i) for i in range(25)]
data.columns = new_index
data.head()

0  \
0  A  hindrance to operations   extracts from the...   
1                                          Scorecard   
2                  Coventry caught on counter by Flo   
3                      Pilgrim knows how to progress   
4                               Hitches and Horlocks   

                                    1  \
0                           Scorecard   
1                 The best lake scene   
2  United s rivals on the road to Rio   
3                 Thatcher facing ban   
4      Beckham off but United survive   

                                               2  \
0                Hughes  instant hit buoys Blues   
1                  Leader  German sleaze inquiry   
2  Thatcher issues defence before trial by video   
3        McIlroy calls for Irish fighting spirit   
4                        Breast cancer screening   

                                               3  \
0       Jack gets his skates on at ice cold Alex   
1                                  Cheerio  boyo   
2  Police help Smith lay down the law at Everton   
3                Leicester bin stadium blueprint   
4                                    Alan Parker   

                                             4  \
0       Chaos as Maracana builds up for United   
1                     The main recommendations   
2  Tale of Trautmann bears two more retellings   
3               United braced for Mexican wave   
4      Guardian readers  are you all whingers    

                                                   5  \
0  Depleted Leicester prevail as Elliott spoils E...   
1                             Has Cubie killed fees    
2                                England on the rack   
3  Auntie back in fashion  even if the dress look...   
4                                   Hollywood Beyond   

                                                 6  \
0                 Hungry Spurs sense rich pickings   
1                           Has Cubie killed fees    
2  Pakistan retaliate with call for video of Walsh   
3                    Shoaib appeal goes to the top   
4                               Ashes and diamonds   

                                                   7  \
0                  Gunners so wide of an easy target   
1                             Has Cubie killed fees    
2               Cullinan continues his Cape monopoly   
3  Hussain hurt by  shambles  but lays blame on e...   
4                   Whingers   a formidable minority   

                                                   8  \
0      Derby raise a glass to Strupar s debut double   
1  Hopkins  furious  at Foster s lack of Hannibal...   
2             McGrath puts India out of their misery   
3                      England s decade of disasters   
4                             Alan Parker   part two   

                                          9  ...  \
0  Southgate strikes  Leeds pay the penalty  ...   
1                    Has Cubie killed fees   ...   
2            Blair Witch bandwagon rolls on  ...   
3      Revenge is sweet for jubilant Cronje  ...   
4                 Thuggery  Toxins and Ties  ...   

                                                  15  \
0           Flintoff injury piles on woe for England   
1                               On the critical list   
2                        South Melbourne  Australia    
3  Putin admits Yeltsin quit to give him a head s...   
4                             Most everywhere   UDIs   

                                                  16  \
0  Hunters threaten Jospin with new battle of the...   
1                          The timing of their lives   
2                                    Necaxa  Mexico    
3         BBC worst hit as digital TV begins to bite   
4                       Most wanted   Chloe lunettes   

                                               17  \
0             Kohl s successor drawn into scandal   
1                                     Dear doctor   
2                             Real Madrid  Spain    
3    

In [6]:
#Converting headlines to lowercase

for index in new_index:
    data[index] = data[index].str.lower()
data.head(1)

0          1  \
0  a  hindrance to operations   extracts from the...  scorecard   

                                 2                                         3  \
0  hughes  instant hit buoys blues  jack gets his skates on at ice cold alex   

                                        4  \
0  chaos as maracana builds up for united   

                                                   5  \
0  depleted leicester prevail as elliott spoils e...   

                                  6                                  7  \
0  hungry spurs sense rich pickings  gunners so wide of an easy target   

                                               8  \
0  derby raise a glass to strupar s debut double   

                                          9  ...  \
0  southgate strikes  leeds pay the penalty  ...   

                                         15  \
0  flintoff injury piles on woe for england   

                                                  16  \
0  hunters threaten jospin with new battle of the...   

                                    17                                    18  \
0  kohl s successor drawn into scandal  the difference between men and women   

                                    19  \
0  sara denver  nurse turned solicitor   

                                               20  \
0  diana s landmine crusade put tories in a panic   

                                                  21                22  \
0  yeltsin s resignation caught opposition flat f...  russian roulette   

         23                  24  
0  sold out  recovering a title  

[1 rows x 25 columns]

In [7]:
headlines = []
for row in range(0, len(data.index)):
    headlines.append(' '.join(str(x) for x in data.iloc[row, :]))

In [8]:
headlines[1]

'scorecard the best lake scene leader  german sleaze inquiry cheerio  boyo the main recommendations has cubie killed fees  has cubie killed fees  has cubie killed fees  hopkins  furious  at foster s lack of hannibal appetite has cubie killed fees  a tale of two tails i say what i like and i like what i say elbows  eyes and nipples task force to assess risk of asteroid collision how i found myself at last on the critical list the timing of their lives dear doctor irish court halts ira man s extradition to northern ireland burundi peace initiative fades after rebels reject mandela as mediator pe points the way forward to the ecb campaigners keep up pressure on nazi war crimes suspect jane ratcliffe yet more things you wouldn t know without the movies millennium bug fails to bite'

In [10]:
headlines_copy = headlines.copy()

## Prediction of Stock sentiment using Machine Learning

In [9]:
### CountVectorizer

from sklearn.feature_extraction.text import CountVectorizer
from sklearn.ensemble import RandomForestClassifier
import pickle

In [10]:
## Implement Bag of words

cv = CountVectorizer(ngram_range=(2,2))
traindataset = cv.fit_transform(headlines)

pickle.dump(cv, open('transform.pkl', 'wb'))

In [11]:
traindataset[0]

<1x584289 sparse matrix of type '<class 'numpy.int64'>'
	with 138 stored elements in Compressed Sparse Row format>

In [12]:
# Implement RandomForest Classifier

randomClassifier = RandomForestClassifier(n_estimators=200, criterion = 'entropy')
randomClassifier.fit(traindataset, train['Label'])

filename = 'stock_sentiment_analysis_model.pkl'
pickle.dump(randomClassifier, open(filename, 'wb'))

In [13]:
# Predict the test set results

test_set = []
for row in range(0, len(test.index)):
    test_set.append(' '.join(str(x) for x in test.iloc[row, 2:]))
test_dataset = cv.transform(test_set)
predictions = randomClassifier.predict(test_dataset)

In [14]:
## Import library to check accuracy

from sklearn.metrics import accuracy_score, classification_report, confusion_matrix


In [15]:
matrix = confusion_matrix(test['Label'], predictions)
print(matrix)
score = accuracy_score(test['Label'], predictions)
print(score)
report = classification_report(test['Label'], predictions)
print(report)

[[139  47]
 [  9 183]]
0.8518518518518519
              precision    recall  f1-score   support

           0       0.94      0.75      0.83       186
           1       0.80      0.95      0.87       192

    accuracy                           0.85       378
   macro avg       0.87      0.85      0.85       378
weighted avg       0.87      0.85      0.85       378



## Prediction of Stock Sentiment using Deep Learning

In [12]:
# headlines_copy

In [26]:
import tensorflow as tf

In [27]:
tf.__version__

'2.3.1'

In [28]:
from tensorflow.keras.layers import Embedding
from tensorflow.keras.preprocessing.sequence import pad_sequences
from tensorflow.keras.models import Sequential
from tensorflow.keras.preprocessing.text import one_hot
from tensorflow.keras.layers import LSTM
from tensorflow.keras.layers import Dense

In [29]:
### Vocabulary Size
voc_size = 5000

## Onehot Representation

In [30]:
help(one_hot)

Help on function one_hot in module tensorflow.python.keras.preprocessing.text:

one_hot(input_text, n, filters='!"#$%&()*+,-./:;<=>?@[\\]^_`{|}~\t\n', lower=True, split=' ')
    One-hot encodes a text into a list of word indexes of size `n`.
    
    This function receives as input a string of text and returns a
    list of encoded integers each corresponding to a word (or token)
    in the given input string.
    
    Arguments:
        input_text: Input text (string).
        n: int. Size of vocabulary.
        filters: list (or concatenation) of characters to filter out, such as
            punctuation. Default: ``!"#$%&()*+,-./:;<=>?@[\]^_`{|}~\t\n``,
              includes basic punctuation, tabs, and newlines.
        lower: boolean. Whether to set the text to lowercase.
        split: str. Separator for word splitting.
    
    Returns:
        List of integers in `[1, n]`. Each integer encodes a word
        (unicity non-guaranteed).



In [31]:
onehot_repr = [one_hot(words, voc_size) for words in headlines_copy]
onehot_repr

[[4662,
  2225,
  2241,
  4790,
  2430,
  1956,
  2507,
  4462,
  2494,
  3789,
  1552,
  300,
  4113,
  4136,
  468,
  4066,
  3528,
  308,
  2572,
  2891,
  2634,
  859,
  4716,
  2595,
  2068,
  1553,
  2801,
  3797,
  3338,
  3730,
  1492,
  1497,
  453,
  2350,
  1553,
  112,
  1689,
  3943,
  3827,
  620,
  1258,
  1079,
  1389,
  278,
  2554,
  4016,
  4306,
  2518,
  678,
  2493,
  2064,
  3698,
  1749,
  1151,
  4662,
  323,
  2241,
  4745,
  3827,
  4213,
  1773,
  2571,
  1696,
  773,
  4208,
  2507,
  4975,
  344,
  3540,
  4772,
  4662,
  1195,
  2113,
  1955,
  620,
  2316,
  1150,
  3827,
  881,
  945,
  3069,
  1119,
  1214,
  3669,
  4682,
  4945,
  3223,
  100,
  1969,
  3827,
  3706,
  934,
  3790,
  2241,
  4113,
  2558,
  2892,
  331,
  2891,
  2265,
  3730,
  3061,
  1132,
  1500,
  3449,
  4696,
  3138,
  1047,
  678,
  2507,
  1118,
  3801,
  3827,
  3219,
  80,
  1214,
  3494,
  2507,
  3032,
  3953,
  716,
  1392,
  842,
  4543,
  834,
  2265,
  1119,
  3036,


In [35]:
max(map(len, onehot_repr))

750

In [36]:
sent_length=750
embedded_docs = pad_sequences(onehot_repr, padding='pre', maxlen = sent_length)
print(embedded_docs)

[[   0    0    0 ... 1906 4662 4349]
 [   0    0    0 ...  341 2241 2837]
 [   0    0    0 ...  185 1779 1803]
 ...
 [   0    0    0 ... 1582 2788 3687]
 [   0    0    0 ... 1392 1751 3827]
 [   0    0    0 ...  678 2507  779]]


In [37]:
embedded_docs[0]

array([   0,    0,    0,    0,    0,    0,    0,    0,    0,    0,    0,
          0,    0,    0,    0,    0,    0,    0,    0,    0,    0,    0,
          0,    0,    0,    0,    0,    0,    0,    0,    0,    0,    0,
          0,    0,    0,    0,    0,    0,    0,    0,    0,    0,    0,
          0,    0,    0,    0,    0,    0,    0,    0,    0,    0,    0,
          0,    0,    0,    0,    0,    0,    0,    0,    0,    0,    0,
          0,    0,    0,    0,    0,    0,    0,    0,    0,    0,    0,
          0,    0,    0,    0,    0,    0,    0,    0,    0,    0,    0,
          0,    0,    0,    0,    0,    0,    0,    0,    0,    0,    0,
          0,    0,    0,    0,    0,    0,    0,    0,    0,    0,    0,
          0,    0,    0,    0,    0,    0,    0,    0,    0,    0,    0,
          0,    0,    0,    0,    0,    0,    0,    0,    0,    0,    0,
          0,    0,    0,    0,    0,    0,    0,    0,    0,    0,    0,
          0,    0,    0,    0,    0,    0,    0,   

In [38]:
###Creating model